#!/usr/bin/env node

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { ImageResponse } from 'next/og';
import { createOgStaticBackground } from '../../lib/og-template';
import { loadOgFonts } from '../../lib/og-image-response';

const CANVAS_WIDTH = 1200;
const CANVAS_HEIGHT = 630;
const OUTPUT_PATH = join(process.cwd(), 'lib/og-background.ts');

function buildOutputSource(dataUri: string): string {
  return [
    '// Generated by scripts/og/bake-og-background.ts.',
    '// Bakes the original OG decorative background into one image so Satori does not render static panel nodes.',
    `export const OG_BACKGROUND_DATA_URI = '${dataUri}' as const;`,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const response = new ImageResponse(createOgStaticBackground(), {
    width: CANVAS_WIDTH,
    height: CANVAS_HEIGHT,
    fonts: await loadOgFonts(),
  });
  const png = Buffer.from(await response.arrayBuffer());
  const dataUri = `data:image/png;base64,${png.toString('base64')}`;

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, buildOutputSource(dataUri), 'utf8');

  console.log(`Wrote ${OUTPUT_PATH}`);
  console.log(`PNG bytes: ${png.byteLength}`);
  console.log(`Data URI bytes: ${Buffer.byteLength(dataUri, 'utf8')}`);
}

main().catch((error: unknown) => {
  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(error);
  }
  process.exit(1);
});
