export type TliFileCategory =
  | 'runtime'
  | 'ops'
  | 'research'
  | 'docs'
  | 'artifact'

export const TLI_BOUNDARY_MANIFEST: Record<string, TliFileCategory> = {
  'scripts/tli/README.md': 'docs',
  'scripts/tli/tli-boundary-manifest.ts': 'docs',
  'scripts/tli/tli-runtime-surface.ts': 'runtime',

  'scripts/tli/batch/collect-and-score.ts': 'runtime',
  'scripts/tli/batch/pipeline-steps.ts': 'runtime',
  'scripts/tli/shared/data-ops.ts': 'runtime',
  'scripts/tli/scoring/calculate-scores.ts': 'runtime',
  'scripts/tli/comparison/calculate-comparisons.ts': 'runtime',
  'scripts/tli/comparison/snapshot-predictions.ts': 'runtime',
  'scripts/tli/comparison/evaluate-predictions.ts': 'runtime',
  'scripts/tli/comparison/evaluate-comparisons.ts': 'runtime',
  'scripts/tli/scoring/load-calibrations.ts': 'runtime',
  'scripts/tli/comparison/auto-tune.ts': 'runtime',
  'scripts/tli/scoring/calibrate-confidence.ts': 'runtime',
  'scripts/tli/scoring/calibrate-noise.ts': 'runtime',
  'scripts/tli/scoring/calibrate-weights.ts': 'runtime',
  'scripts/tli/themes/build-episode-registry.ts': 'runtime',
  'scripts/tli/themes/discover-themes.ts': 'runtime',
  'scripts/tli/themes/theme-keywords.ts': 'runtime',
  'scripts/tli/themes/theme-lifecycle.ts': 'runtime',
  'scripts/tli/themes/theme-state-history.ts': 'runtime',
  'scripts/tli/themes/first-spike-date.ts': 'runtime',
  'scripts/tli/themes/enrich-themes.ts': 'runtime',
  'scripts/tli/comparison/build-query-snapshots.ts': 'runtime',
  'scripts/tli/comparison/analog-evidence.ts': 'runtime',
  'scripts/tli/comparison/materialize-phase0-artifacts.ts': 'runtime',
  'scripts/tli/shared/supabase-admin.ts': 'runtime',
  'scripts/tli/shared/supabase-batch.ts': 'runtime',
  'scripts/tli/shared/utils.ts': 'runtime',
  'scripts/tli/comparison/forecast-serving.ts': 'runtime',
  'scripts/tli/comparison/v4/control.ts': 'runtime',
  'scripts/tli/comparison/v4/shadow.ts': 'runtime',
  'scripts/tli/comparison/v4/evaluator.ts': 'runtime',
  'scripts/tli/comparison/v4/eval-writer.ts': 'runtime',
  'scripts/tli/comparison/v4/records.ts': 'runtime',
  'scripts/tli/comparison/v4/promotion.ts': 'runtime',
  'scripts/tli/collectors/naver-autocomplete.ts': 'runtime',
  'scripts/tli/collectors/naver-datalab.ts': 'runtime',
  'scripts/tli/collectors/naver-finance-theme-list.ts': 'runtime',
  'scripts/tli/collectors/naver-finance-themes.ts': 'runtime',
  'scripts/tli/collectors/naver-news.ts': 'runtime',

  'scripts/tli/batch/run-comparisons.ts': 'runtime',
  'scripts/tli/ops/run-level4-calibration.ts': 'ops',
  'scripts/tli/ops/run-level4-certification.ts': 'ops',
  'scripts/tli/ops/run-level4-drift.ts': 'ops',
  'scripts/tli/ops/run-level4-weight-tuning.ts': 'ops',
  'scripts/tli/ops/promote-comparison-v4.ts': 'ops',
  'scripts/tli/ops/run-first-spike-repair.ts': 'ops',
  'scripts/tli/ops/run-phase0-bridge.ts': 'ops',
  'scripts/tli/ops/run-phase0-materialization.ts': 'ops',
  'scripts/tli/ops/run-theme-state-history-backfill.ts': 'ops',
  'scripts/tli/ops/phase0-bridge.ts': 'ops',
  'scripts/tli/ops/phase0-bridge-certification.ts': 'ops',
  'scripts/tli/comparison/v4/validation.ts': 'ops',
  'scripts/tli/level4/auto-hold.ts': 'ops',
  'scripts/tli/level4/calibrate-comparisons.ts': 'ops',
  'scripts/tli/level4/calibration-artifact.ts': 'ops',
  'scripts/tli/level4/calibration-runtime.ts': 'ops',
  'scripts/tli/level4/certification-rehearsal.ts': 'ops',
  'scripts/tli/level4/certification-runtime.ts': 'ops',
  'scripts/tli/level4/drift-baseline.ts': 'ops',
  'scripts/tli/level4/drift-report.ts': 'ops',
  'scripts/tli/level4/promotion-gate.ts': 'ops',
  'scripts/tli/level4/promotion-runtime.ts': 'ops',
  'scripts/tli/level4/runner-pagination.ts': 'ops',
  'scripts/tli/level4/runtime.ts': 'ops',
  'scripts/tli/level4/tune-weights.ts': 'ops',
  'scripts/tli/level4/weight-artifact.ts': 'ops',

  'scripts/tli/research/backtest-comparisons.ts': 'research',
  'scripts/tli/research/build-future-aligned-dataset.ts': 'research',
  'scripts/tli/research/evaluate-analog-retrieval.ts': 'research',
  'scripts/tli/research/evaluate-forecast-shadow.ts': 'research',
  'scripts/tli/research/comparison-v4-backtest.ts': 'research',
  'scripts/tli/research/comparison-v4-baselines.ts': 'research',
  'scripts/tli/research/comparison-v4-experiments.ts': 'research',
  'scripts/tli/research/comparison-v4-replay.ts': 'research',
  'scripts/tli/research/forecast-ship-gate.ts': 'research',

  'scripts/tli/research/optimizer/dump-data.ts': 'research',
  'scripts/tli/research/optimizer/evaluate.ts': 'research',
  'scripts/tli/research/optimizer/optimize.py': 'research',
  'scripts/tli/research/optimizer/param_space.py': 'research',
  'scripts/tli/research/optimizer/requirements.txt': 'research',
  'scripts/tli/research/optimizer/test_optimize.py': 'research',
  'scripts/tli/research/optimizer/historical-data.json': 'artifact',
  'scripts/tli/research/optimizer/optimized-params.json': 'artifact',
}

export function getTliBoundaryCategory(path: string) {
  return TLI_BOUNDARY_MANIFEST[path]
}
